### ISSUE TITLE
Local npm module "grunt-sri" not found

### ISSUE THREAD

**Issue by jdorfman** [neftaly/grunt-sri#2]
Hello,

I am having issues installing `grunt-sri`.  I am not sure if it is something on my end or what.

```
$ npm install --save-dev grunt-sri
npm WARN saveError Unexpected end of input
/Users/jdorfman
└─┬ grunt-sri@0.0.5
  └── async@0.9.2

npm WARN EJSONPARSE Failed to parse json
npm WARN EJSONPARSE No data, empty input at 1:1
```

```
$ grunt
>> Local Npm module "grunt-sri" not found. Is it installed?
Warning: Task "sri" not found. Use --force to continue.
Aborted due to warnings.
```

Environment:
- Darwin Kernel Version 15.2.0 (OS X 10.11.2)
- Node: v5.3.0
- npm: 3.3.12
- grunt-cli v0.1.13
- grunt v0.4.5

Any help would be appreciated.  Thank you!

**Comment by jonathanKingston** [comment]
@jdorfman this looks a whole lot like the your `package.json` has a parse error in it somewhere.

Feel free to paste it here etc.

I just installed this myself and seems to work fine, certainly not getting the errors you are.

**Comment by jdorfman** [comment]
@jonathanKingston interesting let me check

**Comment by jdorfman** [comment]
Totally my bad.  Thanks @jonathanKingston
